name: UPM Sync
on:
  push:
    branches:
      - 'main'
      - 'feature/automate-release'
  workflow_dispatch:
env:
  base: https://github.com/facebook/facebook-sdk-for-unity/archive/refs/tags/sdk-version
  version: 11.0.0
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Config
        run: |
          git config --local user.email "contact@gameworkstore.com"
          git config --local user.name "game-workstore-bot"
          
      - uses: actions/checkout@v2
        with:
          path: base

      - name: Check out my other private repo
        uses: actions/checkout@v2
        with:
          repository: facebook/facebook-sdk-for-unity
          ref: ${{ env.version }}
          path: facebook

      - name: List
        run: |
          ls

      - name: Download Package
        if: false
        env:
          file: content.tar.gz
        run: |
          sudo apt-get install unzip
          rm -rf Staging
          mkdir Staging
          cd Staging
          #curl ${{ env.base }}-${{ env.version }}.tar.gz --output ${{ env.file }}
          wget ${{ env.base }}-${{ env.version }}.tar.gz -o ${{ env.file }}
          ls
          file ${{ env.file }}
          tar -vxf ${{ env.file }}
          ls

  disabled:
    runs-on: ubuntu-latest
    if: false
    steps:
      - name: Install DiffUtils
        if: false
        run:
          sudo apt-get install diffutils
      
      - name: Update README
        if: false
        run: |
          if ! cmp --silent "README.md" "Assets/Package/README.md"; then
              echo "different"
              cp -f README.md Assets/Package/README.md
              git add --a
              git commit -m "Updated README.md"
              git push origin
          fi

      - name: Cook UPM
        if: false
        run: |
          git subtree split -P Assets/Package/ -b upm
          git checkout upm
          ls

      - name: Push changes
        if: false
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: upm
          force: true